============================= test session starts ==============================
platform linux -- Python 3.10.2, pytest-7.0.1, pluggy-1.0.0
Matplotlib: 3.5.1
Freetype: 2.6.1
rootdir: /home/amangoel185/Documents/fellowship/hist, configfile: pyproject.toml
plugins: mpl-0.14.0, anyio-3.5.0
collected 6 items

tests/test_txtreprs.py ...Fatal Python error: Segmentation fault

Current thread 0x00007f4c37738740 (most recent call first):
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/boost_histogram/_internal/hist.py", line 746 in sum
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/boost_histogram/_internal/hist.py", line 612 in __repr__
  File "/home/amangoel185/Documents/fellowship/hist/tests/test_txtreprs.py", line 22 in test_ND_empty_repr_weight
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/python.py", line 1718 in runtest
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/runner.py", line 168 in pytest_runtest_call
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/runner.py", line 261 in <lambda>
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/runner.py", line 340 in from_call
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/runner.py", line 260 in call_runtest_hook
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/runner.py", line 221 in call_and_report
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/runner.py", line 132 in runtestprotocol
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/runner.py", line 113 in pytest_runtest_protocol
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/main.py", line 322 in _main
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/config/__init__.py", line 165 in main
  File "/home/amangoel185/.virtualenvs/hist/lib/python3.10/site-packages/_pytest/config/__init__.py", line 188 in console_main
  File "/home/amangoel185/.virtualenvs/hist/bin/pytest", line 8 in <module>

Extension modules: markupsafe._speedups, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver (total: 18)
